In [7]:
import climetlab as cml
cml.settings.get("cache-directory") 

data = cml.load_source("cds",
                       "reanalysis-era5-single-levels",
                       {'date': 20230109, 
                        'time': 18, 
                        'param': ['lsm', '2t', 'msl', '10u', '10v', 'tp', 'z'],
                          'grid': [0.25, 0.25], 
                          'area': [90, 0, -90, 360],
                            'type': 'fc', 
                            'stream': 'scda', 
                            'product_type': 'reanalysis'})

2024-12-24 14:52:10,809 INFO [2024-09-28T00:00:00] **Welcome to the New Climate Data Store (CDS)!** This new system is in its early days of full operations and still undergoing enhancements and fine tuning. Some disruptions are to be expected. Your
[feedback](https://jira.ecmwf.int/plugins/servlet/desk/portal/1/create/202) is key to improve the user experience on the new CDS for the benefit of everyone. Thank you.
2024-12-24 14:52:10,811 INFO [2024-09-26T00:00:00] Watch our [Forum](https://forum.ecmwf.int/) for Announcements, news and other discussed topics.
2024-12-24 14:52:10,813 INFO [2024-09-16T00:00:00] Remember that you need to have an ECMWF account to use the new CDS. **Your old CDS credentials will not work in new CDS!**
2024-12-24 14:52:10,814 WARNING [2024-06-16T00:00:00] CDS API syntax is changed and some keys or parameter names may have also changed. To avoid requests failing, please use the "Show API request code" tool on the dataset Download Form to check you are using the correct syntax for your API request.

In [10]:
data_df = data.to_pandas()

In [13]:
data_df

,lat,lon,value,datetime,domain,levtype,date,time,step,param,class,type,stream,expver
0,90.0,0.00,0.000000,2023-01-09 18:00:00,g,sfc,20230109,1800,0,lsm,ea,an,oper,0001
1,90.0,0.25,0.000000,2023-01-09 18:00:00,g,sfc,20230109,1800,0,lsm,ea,an,oper,0001
2,90.0,0.50,0.000000,2023-01-09 18:00:00,g,sfc,20230109,1800,0,lsm,ea,an,oper,0001
3,90.0,0.75,0.000000,2023-01-09 18:00:00,g,sfc,20230109,1800,0,lsm,ea,an,oper,0001
4,90.0,1.00,0.000000,2023-01-09 18:00:00,g,sfc,20230109,1800,0,lsm,ea,an,oper,0001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1038235,-90.0,358.75,27718.275879,2023-01-09 18:00:00,g,sfc,20230109,1800,0,z,ea,an,oper,0001
1038236,-90.0,359.00,27718.275879,2023-01-09 18:00:00,g,sfc,20230109,1800,0,z,ea,an,oper,0001
1038237,-90.0,359.25,27718.275879,2023-01-09 18:00:00,g,sfc,20230109,1800,0,z,ea,an,oper,0001
1038238,-90.0,359.50,27718.275879,2023-01-09 18:00:00,g,sfc,20230109,1800,0,z,ea,an,oper,0001
1038239,-90.0,359.75,27718.275879,2023-01-09 18:00:00,g,sfc,20230109,1800,0,z,ea,an,oper,0001

In [14]:
print(data)

GRIBReader(/var/folders/0r/nzg1qk0n1qd552y9hhd30dnc0000gn/T/climetlab-leroy/cds-retriever-1a1d7637aaaf5616ccdf2c650bb81dd5b6613e9f032826fa57c364fbd61136c5.cache)

In [15]:
import os

with open(os.path.expanduser("~/.cdsapirc"), "r") as file:
    print(file.read())

url: https://cds.climate.copernicus.eu/api
key: cb2bc303-74c7-4256-b92d-5c998a0fcf88